# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paris Holley | The grown up wonder child
email: mail@parisholley.com
description: Peek inside the mind of a entrepreneur, musician, programmer, photographer who can't figure out what he wants to be when he grows up.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.parisholley.com" # the base hostname & protocol for your site
twitter_username: parisholley
github_username:  parisholley

# Build settings
markdown: kramdown
